#!/bin/bash -x
if [ ! "$1" ]; then
	echo "No syslinux directory specified"
	exit 1
fi

syslinux=$1
for file in mboot.c32 chain.c32 menu.c32 vesamenu.c32 pxechn.c32 memdisk; do
	cp `find $syslinux -name "$file"` $file
done
