#!/bin/bash -x
if [ ! "$1" ]; then
	echo "No syslinux directory specified"
	exit 1
fi

syslinux=$1
for file in mboot.c32 chain.c32 vesamenu.c32 memdisk; do
	ln -s `find $syslinux -name "$file" -type f` $file
done
